### PR TITLE
update flask to the correct version

### PR DESCRIPTION
**Pull request by afuechsel**
Flask 1.2.0 is outdated and will not run in the examples.

### CODE REVIEW

**Comment by afuechsel** [comment]
Can you please explain, why you didn't merge? It's the same issue as with the first part of that Udacity Nanodegree. You are using an outdated version of flask, that is no longer working. My previous PR for the course repo of the first part if that course was accepted @Dhadhazi ?

**Comment by Dhadhazi** [comment]
I understand that it might be a major update, even a necessary one for the project. I was advised to close it since there is an "internal version" of the same project, and it might cause problems having a different version of Flask in the repo.

**Comment by afuechsel** [comment]
Well, the thing is, the project is not starting at all with this outdated version. It is no longer supported. So without my MR you have an invalid and broken course repo. I'd suggest you check again and merge.

**Comment by afuechsel** [comment]
This MR of mine addressed the same issue in the first part of the course and was accepted. 

https://github.com/udacity/nd064_course_1/pull/82

**Comment by Dhadhazi** [comment]
First, thanks for all the effort of caring about the course and sending me this message. 
Second, I will take a deeper look at it and consult with colleagues on it.

And thanks again, you are awesome!

**Comment by Dhadhazi** [comment]
I want to thank you again for this pull request and the fact that you cared! Thank you very much!

**Pull request merged**
